services:
    tee:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - tee:/app/packages/client-twitter/src/tweetcache
            - tee:/app/db.sqlite
        environment:
            - OPENAI_API_KEY=
            - REDPILL_API_KEY=
            - ELEVENLABS_XI_API_KEY=
            - ELEVENLABS_MODEL_ID=eleven_multilingual_v2
            - ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM
            - ELEVENLABS_VOICE_STABILITY=0.5
            - ELEVENLABS_VOICE_SIMILARITY_BOOST=0.9
            - ELEVENLABS_VOICE_STYLE=0.66
            - ELEVENLABS_VOICE_USE_SPEAKER_BOOST=false
            - ELEVENLABS_OPTIMIZE_STREAMING_LATENCY=4
            - ELEVENLABS_OUTPUT_FORMAT=pcm_16000
            - TWITTER_DRY_RUN=false
            - TWITTER_USERNAME=
            - TWITTER_PASSWORD=
            - TWITTER_EMAIL=
            - X_SERVER_URL=https://api.red-pill.ai/v1
            - BIRDEYE_API_KEY=
            - SOL_ADDRESS=So11111111111111111111111111111111111111112
            - SLIPPAGE=1
            - RPC_URL=https://api.mainnet-beta.solana.com
            - HELIUS_API_KEY=
            - SERVER_PORT=3000
            - WALLET_SECRET_SALT=secret_salt
            - DIFY_BASE_URL=http://app.dify.superagentai.online/v1
            - DIFY_API_KEY=app-I3OpoFJF4Ajch5DJXVqex23a
            - TELEGRAM_BOT_TOKEN=7971427881:AAHhQdFyL40jTwG7lVKQ8CZlgXpZzIF7UJE
            - OPENAI_API_KEY=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
            - ANTHROPIC_API_KEY=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
        ports:
            - "3000:80"
        restart: always

volumes:
    tee:
